name: Build and Package

on:
  push:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "2.3.3"

      - name: Build and package
        run: |
          bash Taskfile build
          bash Taskfile package

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          path: dist/smart-tab-group-*.zip
