name: Build and Package

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and package
        run: |
          bash Taskfile build

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: firefox build
          path: build/firefox/*

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: chrome build
          path: build/chrome/*
